name: katinat
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  cached_network_image_builder: ^0.3.0
  carousel_slider: ^4.2.1
  cloudinary: ^1.2.0
  cloudinary_public: ^0.23.1
  dart_jsonwebtoken: ^2.13.0
  device_info_plus: ^10.1.0
  email_otp: ^2.1.2
  email_validator: ^2.1.17
  firebase_core: ^2.30.0
  firebase_database: ^10.5.2
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  flutter_email_sender: ^6.0.3
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  flutter_otp_text_field: ^1.1.3+2
  http: ^1.2.1
  image_picker: ^1.1.1
  internet_connection_checker_plus: ^2.3.0
  intl: ^0.19.0
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  text_form_field_validator: ^0.0.3

flutter_icons:
  android: true
  image_path_android: assets/images/logo.png

flutter_native_splash:
  color: 'ffffff'
  image: assets/images/logo.png

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/files/
  fonts:
    - family: MainFont
      fonts:
        - asset: assets/fonts/MainFont.ttf
