name: katinat
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  dart_jsonwebtoken: ^2.13.0
  device_info_plus: ^10.1.0
  firebase_app_check: ^0.2.2+4
  firebase_core: ^2.30.0
  firebase_database: ^10.5.2
  firebase_storage: ^11.7.3
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  http: ^1.2.1
  internet_connection_checker_plus: ^2.3.0
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  text_form_field_validator: ^0.0.3

flutter_icons:
  android: true
  image_path_android: assets/images/logo.png

flutter_native_splash:
  color: 'ffffff'
  image: assets/images/logo.png

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/files/
  fonts:
    - family: MainFont
      fonts:
        - asset: assets/fonts/MainFont.ttf
