// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByimoQHz7FApXUHegzaKK075EAXCKhQAM',
    appId: '1:360183955062:android:befb5d73a02cb287bb2957',
    messagingSenderId: '360183955062',
    projectId: 'katinat-897d7',
    databaseURL: 'https://katinat-897d7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'katinat-897d7.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdAA6D6w5PRhuexwSprPWpb3jX4ZsiJb4',
    appId: '1:360183955062:web:b7ca1b892ed3626bbb2957',
    messagingSenderId: '360183955062',
    projectId: 'katinat-897d7',
    authDomain: 'katinat-897d7.firebaseapp.com',
    databaseURL: 'https://katinat-897d7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'katinat-897d7.appspot.com',
    measurementId: 'G-ZRC57S46C2',
  );
}
